### ISSUE TITLE
IAM Policy Scanner Might Need to Have require_any Mode

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#1387]
With the rule below, a project would not have a violation if there is both a user and group from foobar.com.  But there might be a use case for just requiring one of the members.  i.e. we need a `require_any` mode.  Shelving this until we have a real use case for this.
```
  - name: All projects must have owner from my domain
    mode: required
    resource:
      - type: project
        applies_to: self
        resource_ids:
          - '*'
    inherit_from_parents: true
    bindings:
      - role: roles/owner
        members:
          - user:*@foobar.com
          - group:*@foobar.com
```
