### ISSUE TITLE
Support empty whitelists for IAM roles

### ISSUE THREAD

**Issue by dufton** [forseti-security/forseti-security#1963]
Sometimes we prevent anyone holding an IAM role, through either an empty whitelist, or an all-matching blacklist. This is currently not supported:
```
rules:
  - name: Empty whitelist for viewer role on project
    mode: whitelist
    resource:
    - type: project
      applies_to: self
      resource_id:
        - 'my-project'
    bindings:
      - role: roles/viewer
        members: []
  - name: All-matching blacklist for viewer role on project
    mode: blacklist
    resource:
    - type: project
      applies_to: self
      resource_id:
        - 'my-project'
    bindings:
      - role: roles/viewer
        members:
        - '*'
```

Low priority because these are two possible workarounds: using a dummy value in the whitelist, or listing all member types in the blacklist.
```
rules:
  - name: Empty whitelist for viewer role on project
    ...
    bindings:
      - role: roles/viewer
        members:
        - user:nobody
  - name: All-matching blacklist for viewer role on project
    ...
    bindings:
      - role: roles/viewer
        members:
        - allUsers
        - allAuthenticatedUsers
        - user:*
        - group:*
        - serviceAccount:*
        - domain:*
```
