### ISSUE TITLE
Firewall scanner to whitelist the `default-allow-internal` returns a violation and a recommendation to delete the `default-allow-internal` firewall

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#2012]
This is the rule that is used.

```
rules:
  - rule_id: 'allow_default_internal'
    description: allow all tcp, udp, icmp internal traffic
    mode: whitelist
    match_policies:
      - direction: ingress
        allowed: ['*']
    verify_policies:
      - allowed:
        - IPProtocol: 'tcp'
          ports: ['all']
        - IPProtocol: 'udp'
          ports: ['all']
        - IPProtocol: 'icmp'
        sourceRanges:
          - '10.128.0.0/9'
```
