### ISSUE TITLE
Email send error

### ISSUE THREAD

**Issue by umairidris** [forseti-security/forseti-security#3005]
Terraform config (JSON):
```
{
 "module": {
  "forseti": {
   "composite_root_resources": [
    "organizations/123",
    "folders/345"
   ],
   "domain": "google.com",
   "project_id": "abc",
   "source": "./terraform-google-forseti"
  }
 }
}
```

Error:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/notifier/notifiers/inventory_summary.py", line 169, in _send_email
>     content_type='text/html')
>   File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/common/util/email/sendgrid_connector.py", line 122, in send
>     raise util_errors.EmailSendError
> google.cloud.forseti.common.util.errors.EmailSendError

Since an email is not set I would expect the behaviour to be that Forseti does not try to send an email.

**Comment by blueandgold** [comment]
Hi Umair, as you can see from the code / screenshot here, there are various checks before the inventory summary email will be sent. What does your actual populated `forseti_conf_server.yaml` look like?

https://github.com/forseti-security/forseti-security/blob/dev/google/cloud/forseti/notifier/notifiers/inventory_summary.py#L261-L300
![image](https://user-images.githubusercontent.com/6977544/62186076-b98b9e00-b319-11e9-81df-f0c1addb4936.png)

**Comment by umairidris** [comment]
Ah, I think I see it:

```
    inventory:
      gcs_summary:
        enabled: true
        # data_format may be one of: csv (the default) or json
        data_format: csv
        # gcs_path should begin with "gs://"
        gcs_path: gs://forseti-server-e982fd1b/inventory_summary
      email_summary:
        enabled: true
```

In the Forseti Terraform module, `inventory_email_summary_enabled` is enabled by default. But I would assume it requires `sendgrid_api_key`, `forseti_email_sender`, and `forseti_email_sender` to work.

Perhaps email notifications should be false by default?

cc @morgante
