### ISSUE TITLE
Cloud Audit Logging Rule at the Org Level

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#3079]
I'm having difficulty in getting the Cloud Audit Logging rule to work properly. There are some examples on folder and project level rules, but not on org level. Can someone please provide an example org level rule? Every time I build one in the same formatting as the project or folder level rule, it causes my scanner to break with "serverMessage": "Error occurred during the scanning process."

**Comment by kevensen** [comment]
Example rule:
```
 - name: 'Require ADMIN_READ, DATA_READ, DATA_WRITE for all services'
    resource:
      - type: organization
        resource_ids:
          - 'ORG_ID_HERE'
    service: 'allServices'
    log_types:
      - 'ADMIN_READ'
      - 'DATA_READ'
      - 'DATA_WRITE'
```

**Comment by kevensen** [comment]
Organizations are an acceptable resource type.  I'll continue to dig.
https://github.com/forseti-security/forseti-security/blob/b54faf68d869842e8a43472ff980e28e2ce8d3c6/google/cloud/forseti/scanner/scanners/audit_logging_scanner.py#L125-L130

**Comment by kevensen** [comment]
The rule provided is valid.  The next step is to change the verbosity of the server logs, if applicable.

1. Open an SSH session to the server VM

2. Sudo to root
```bash
sudo -i
```
3. Open the Forseti server system unit file for edit
```bash
vi /lib/systemd/system/forseti.service
```
4.  At the end of the **ExecStart** clause, append **--log_level=debug**.  It should resemble the following.
```bash
ExecStart=/usr/local/bin/forseti_server --endpoint '[::]:50051' --forseti_db mysql://root@127.0.0.1:3306/forseti_security?charset=utf8 --config_file_path /home/ubuntu/forseti-security/configs/forseti_conf_server.yaml --services explain inventory model scanner notifier --log_level=debug
```
5. Restart the Forseti server process
```bash
systemctl restart forseti
```
Re-run the scanner and let's see if there is additional log output in Stackdriver.

**Comment by kevensen** [comment]
[forseti-security][2.16.0] google.cloud.forseti.services.scanner.service(_run_scanner): 'list' object has no attribute 'get' Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.16.0-py3.6.egg/google/cloud/forseti/services/scanner/service.py", line 121, in _run_scanner scanner_name) File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.16.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py", line 107, in run None, scanner_name).build() File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.16.0-py3.6.egg/google/cloud/forseti/scanner/scanner_builder.py", line 65, in build scanner = self._instantiate_scanner(scanner.get('name')) File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.16.0-py3.6.egg/google/cloud/forseti/scanner/scanner_builder.py", line 132, in _instantiate_scanner rules) File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.16.0-py3.6.egg/google/cloud/forseti/scanner/scanners/audit_logging_scanner.py", line 55, in __init__ self.rules_engine.build_rule_book(self.global_configs) File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.16.0-py3.6.egg/google/cloud/forseti/scanner/audit/audit_logging_rules_engine.py", line 63, in build_rule_book snapshot_timestamp=self.snapshot_timestamp) File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.16.0-py3.6.egg/google/cloud/forseti/scanner/audit/audit_logging_rules_engine.py", line 132, in __init__ self.add_rules(rule_defs) File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.16.0-py3.6.egg/google/cloud/forseti/scanner/audit/audit_logging_rules_engine.py", line 174, in add_rules for (i, rule) in enumerate(rule_defs.get('rules', [])): AttributeError: 'list' object has no attribute 'get'

**Comment by kevensen** [comment]
audit_logging_rules.yaml was missing **rules:** as first line in file.

```yaml
 - name: 'Require ADMIN_READ, DATA_READ, DATA_WRITE for all services'
   resource:
     - type: organization
       resource_ids:
         - 'ORG_ID_HERE'
   service: 'allServices'
   log_types:
     - 'ADMIN_READ'
     - 'DATA_READ'
     - 'DATA_WRITE'
```
Corrected to be:
```yaml
rules:
 - name: 'Require ADMIN_READ, DATA_READ, DATA_WRITE for all services'
   resource:
     - type: organization
       resource_ids:
         - 'ORG_ID_HERE'
   service: 'allServices'
   log_types:
     - 'ADMIN_READ'
     - 'DATA_READ'
     - 'DATA_WRITE'
```
