### ISSUE TITLE
My custom rule

### ISSUE THREAD

**Issue by Kumurzhi-Vladimir** [forseti-security/forseti-security#3234]
Version - 2.21.0
Module - scanner
Install from qwiklabs - [qwiklabs](https://www.qwiklabs.com/focuses/6120?parent=catalog)

Hello, dear developers. Could you please write me how to create my own rule and run it?

For example - I need to find "default" network in my project and I wanna see output like this: "serverMessage": "Retrieved 1 violations for resource 'default_network_rule'"

But I dont understand how to create this rule and run it. I have tried to add it into the forseti_conf_server_xxxxxxx.yaml to scanners, and it looked like this: 

```
scanners:   
        - name: default_network_rule
          enabled: true
```

and then, into folder "rules" I added "default_network_rule.yaml" which consist following text:

```
rules:
  - name: Ensure the default network does not exist in a project
    mode: blacklist
    resource:
      - type: project
        resource_ids:
          - '*'
    network: 'default'
```

If you have some time, please write the simple manual how to write own custom rule, add it and run it.
Thank you very much.
