### ISSUE TITLE
IAM Policy Scanner Can Not Find Violations on Public Dataset

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3406]
In the test environment, this is a dataset that is configured with `allAuthenticatedUsers`, but the IAM policy scanner is unable to find this violation with the following rule, despite supporting it.  But this works on buckets with a similar IAM policy, for which violation is found.

```
IAM_TYPE_RESOURCE_MAP = {
   ResourceType.BILLING_ACCOUNT: BillingAccount,
   ResourceType.BUCKET: Bucket,
    ResourceType.DATASET: Dataset,
   ResourceType.FOLDER: Folder,
   ResourceType.ORGANIZATION: Organization,
   ResourceType.PROJECT: Project,
}
```

Example Rule:
```
  - name: Prevent public authenticated users from having access to buckets via IAM
    mode: blacklist
    resource:
      - type: dataset
        applies_to: self
        resource_ids:
          - '*'
    inherit_from_parents: true
    bindings:
      - role: '*'
        members:
          - allAuthenticatedUsers
```
