### ISSUE TITLE
Firewall rules scanner doesn't work when a range of ports is entered in the `ports` field

### ISSUE THREAD

**Issue by red2k18** [forseti-security/forseti-security#3494]
Firewall rules scanner works only when a specific ports number or `all` is entered in the `ports` field.
```
- rule_id: 'TestRuleId'
    description: TestDesc
    mode: blacklist
    match_policies:
      - direction: ingress
        allowed: ['*']
        sourceRanges: ['X.X.X.X/X']
    verify_policies:
      - allowed:
        - IPProtocol: 'tcp'
          ports:
            - '5400-5500'
```
