### ISSUE TITLE
Issue with Config Validator notifications

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3506]
## Story
A [user](https://forsetisecurity.slack.com/archives/CAZCH95EF/p1574253087244800) is having issues with the [enforce_label](https://github.com/forseti-security/policy-library/blob/master/samples/enforce_label.yaml) CV template sample.

### Policy
```
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPEnforceLabelConstraintV1
metadata:
  name: require_labels
spec:
  severity: high
  match:
    target: ["organization/<redacted>/*"]
  parameters:
    mandatory_labels: 
      - "wid": ".*"
     resource_types_to_scan:
      - "compute.googleapis.com/Instance"
      - "cloudresourcemanager.googleapis.com/Project"
```

### Forseti Configuration
```
scanners:
  - name: config_validator
    enabled: true
notifier:
  resources:
    - resource: config_validator_violations
      should_notify: true
      notifiers:
        # Upload violations to GCS.
        - name: gcs_violations
          configuration:
            data_format: csv
            # gcs_path should begin with "gs://"
            gcs_path: <redacted>
violation:
    cscc:
      enabled: true
      source_id: <redacted>
```

## Issues
The issue is this seems to work fine at the project level.  All of the projects without a label of "wid" are alerting properly to CSCC.
However, at the instance level, some weird things are happening: 

1. None of the instances alert via csv to the alert bucket I have set up, but all of the projects are in the csv.
2. All of the instances are alerting in CSCC no matter what label I have assigned to them (even if I have the correct "wid" label), but they are only showing in "Inactive Findings".  None of the instance alerts appear when I have the "Show Only Active Findings" slide enabled.
When I run Forseti manually with the - "cloudresourcemanager.googleapis.com/Project" line in the config, the notifier logs state "Retrieved 52 violations for resource 'config_validator_violations'.
3. However, if I remove projects from the scan, then I get "no violations" for config_validator_violations, even though they (instance alerts) show up as inactive in CSCC.
