### ISSUE TITLE
Location Rule not working

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3550]
## Story
A [user](https://forsetisecurity.slack.com/archives/CAZCH95EF/p1576196173376300) on Slack is trying to use the Location Scanner with Forseti v2.25.0 on GKE. The following rule is not producing violations even though they have buckets in the US:

```
rules:
   - name: All buckets in organization must not be in the US.
     mode: blacklist
     resource:
       - type: organization
         resource_ids:
           - {ORG_ID}
     applies_to:
       - type: 'bucket'
         resource_ids:
           - '*'
     locations:
       - 'us*'
```

## Troubleshooting
Originally the rule was configured at the project level and was using a wildcard for the resource/resource_ids. The user tried changing it to resource/type = `organization` and using their actual Org Id for the resource/resource_ids. @gkowalski-google was able to reproduce the issue (on GCE), but the changes mentioned above resolved it. I have asked the user to check for any errors in Stackdriver.
