### ISSUE TITLE
Run raw docker image as an app fails to run wit `+ false` output

### ISSUE THREAD

**Issue by dinigo** [forseti-security/forseti-security#3694]
When I run forseti docker Image, I've tried `forsetisecurity/forseti:latest` image and with the `grc.io` versions `v2.25.0` and `v2.24.2`, it fails to start. With the dockerhub one.
```
$ docker run -P --rm gcr.io/forseti-containers/forseti:v2.24.2
+ false
+ false
+ false
```
If I configure a service for docker stack it happens the same
```yaml
version: '3.6'

services:
  database:
    image: mysql
    # rest of database conofig

  forseti-server:
    image: gcr.io/forseti-containers/forseti:v2.24.2
    depends_on:
      - database
    volumes:
      - ./config.yaml:/forseti-security/forseti_conf_server.yaml
    environment:
      - RUN_SERVER=true
      - SERVICES=inventory
      - SQL_HOST=database
      - SQL_DATABASE_NAME=forseti_security
      - SQL_DB_USER=forseti
      - SQL_DB_PASSWORD=forseti
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/server-service-account
    secrets:
      - server-service-account
```
Running this produces output:
```
+ false
+ false
+ false
```
When it sould run the `docker_entrypoint.sh`. Even if I override the entrypoint: by hand
```
```yaml
version: '3.6'
services:
  forseti-server:
    entrypoint: docker_entrypoint.sh
    # rest of forseti config
```
But running the `v2.25.0` does the same even though the `ENTRYPOINT` has changed in the `Dockerfile`
it produces the same output.

What does this `+ false` output mean? How is it supposed to be run?

**Comment by gkowalski-google** [comment]
Hi @dinigo, it looks like your close. I recently added a [docker-compose.yml file](https://github.com/forseti-security/forseti-security/blob/master/docker-compose.yml) that I think helps make Forseti easier to run with docker. You just need to export 4 env vars and then run `make docker_run` (details for these values can be found in the compose file):
- GOOGLE_APPLICATION_CREDENTIALS
- FORSETI_SERVER_CONFIG_PATH
- FORSETI_SQL_CONNECTION
- FORSETI_SQL_INSTANCE

**Comment by dinigo** [comment]
Yes! this actually works!

I found that the error/behavior I was experiencing Is caused by the `docker_entrypoint.sh` script being run. I can't get it to work
```
+ false
+ false
+ false
```
If I force the _entrypoint_ to some other `entrypoint: forseti inventory create` it works. But I would rather have this script, [the original](https://github.com/forseti-security/forseti-security/blob/master/Dockerfile#L97) working. It's far more versatile and configurable through environment variables, which is what I need to run a server and a client without overriding the entrypoint. I've been 

------

Just as a side note, you are using mysql (as written in the schema) but with the postgresql,default port 5432, so I deployed a PosgreSQL Cloud SQL instance. I got confused but it works. In [the docs](https://cloud.google.com/sql/docs/mysql/connect-docker#connect-client) they use the default one and it may save some further confusion to some other

**Comment by red2k18** [comment]
@dinigo Checking in to see if you were able to run the image?

**Comment by dinigo** [comment]
@red2k18 I ran it like so:
```yaml
version: '3.6'
services:

  database:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysqldb:/var/lib/mysql
    environment:
      - MYSQL_USER=forseti
      - MYSQL_PASSWORD=forseti
      - MYSQL_DATABASE=forseti
      - MYSQL_RANDOM_ROOT_PASSWORD

  forseti-server:
    image: forseti-security/forseti-server:43d143d8
    depends_on:
      - database
    volumes:
      - ${FORSETI_CONFIG}:/forseti-security/forseti_conf_server.yaml
    environment:
      - SERVICES=inventory
      - SQL_DB_CONNECTION_STRING=mysql+pymysql://forseti:forseti@database:3306/forseti
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/server-service-account
    secrets:
      - server-service-account

  forseti-client:
    image: forseti-security/forseti-server:43d143d8
    depends_on:
      - forseti-server
    entrypoint:
      - forseti
      - '--endpoint=forseti-server:50051'
      - inventory
      - create

secrets:
  client-service-account:
    file: ${SERVICE_ACCOUNT_CLIENT}
  server-service-account:
    file: ${SERVICE_ACCOUNT_SERVER}
```

And it works, but because this version overrides the `entrypoint.sh`. I think either:
- Do not provide any entrypoint. Let the end user decide which to use
- Provide the `entrypoint.sh` (functional) and let the user choose the command (client or server)

I've got into the container with bash. Checked that the entrypoint was there with `cat`. Tried to run from within, and the result was the same `+false +false +false`.

Can you @Red-Five check that this happens for you too?
