### ISSUE TITLE
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry '....' for key 'PRIMARY'

### ISSUE THREAD

**Issue by abhishekupadhyaya** [forseti-security/forseti-security#3757]
Hi,

We use `release-2.25.1` and run Forseti scans for 3 GCP organization as composite_root_resources. Here is part of our conf file:
```
inventory:

    # Root resource to start crawling from, formatted as
    root_resource_id: ""
    composite_root_resources:
      - "organizations/<id1>"
      - "organizations/<id2>"
      - "organizations/<id3>"
```

The billing account of org `id3` is same as the billing account of org `id1`. We are getting following error, which we think is related to these 2 orgs being tied to same billing account:

`sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1062, "Duplicate entry 'billing_account/<billing_account>' for key 'PRIMARY'") [SQL: 'INSERT INTO <some_uuid>_resources (cai_resource_name, cai_resource_type, full_name, type_name, parent_type_name, name, type, policy_update_counter, display_name, email, data) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (('//cloudbilling.googleapis.com/billingAccounts/<billing_account>' .......`

Could you help us resolve this issue?

Thank you,
Abhishek
