### ISSUE TITLE
False Positive Audit Logging Violations

### ISSUE THREAD

**Issue by jeffreycao1** [forseti-security/forseti-security#3764]
Hi,

We are running Forseti v2.25.1.

For the Audit Logging Scanner we are getting false positive violations even though the projects are configured correctly.

Here is the rule we are using:
```
rules:
  - name: '[CIS_2.1] - Require logging for all services and all users in a project'
    resource:
      - type: project
        resource_ids:
          - '*'
    service: 'allServices'
    log_types:
      - 'ADMIN_READ'
      - 'DATA_READ'
      - 'DATA_WRITE'
```

Here is an image of the gcloud command for one of the affected projects
![6f2ed5e6-99a5-4a7f-bd3b-ad2b41ec0541(1)](https://user-images.githubusercontent.com/67289243/85326223-cb21eb00-b481-11ea-8e36-8266242f41e0.PNG)

Here is a sample of the resource data and violation data for that project we get from running Forseti:
```
"audit_configs": [
      {
        "audit_log_configs": [
          {
            "log_type": 1
          },
          {
            "log_type": 3
          },
          {
            "log_type": 2
          }
        ],
        "service": "allServices"
      }
    ]
```
*Removed bindings section above.

```
"violation_data": {
    "full_name": "organization/<org_id>/project/<project_id>/",
    "log_type": "DATA_READ",
    "service": "allServices"
  }
```
*Substituted out the org and project ids above.

Could you help us resolve the issue please.

Thank you,
Jeffrey
