### ISSUE TITLE
No way to reach community support

### ISSUE THREAD

**Issue by janmasarik** [forseti-security/forseti-security#3794]
Hey guys 👋 ,

Thanks for your amazing work! :-)

I tried to reach out the community with a question regarding IAM rule creation, but the [slack link](https://forsetisecurity.org/docs/latest/use/get-help.html) is expired, and I've received the following mail[1] from discuss@forsetisecurity.org.

Is there any other way how to ask it? :-) 

Thanks in advance!

[1]
```
Hello jan.masarik@kiwi.com,

We're writing to let you know that the group you tried to contact (discuss) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/forsetisecurity.org/bin/topic.py?topic=25838.

Thanks,

forsetisecurity.org admins
```

**Comment by gkowalski-google** [comment]
Hi @janmasarik, thanks for letting us know about the Slack issue. I have not seen that error in regards to the email address, will look into it. You can also provide the issue details in this ticket and we can work on it.

**Comment by janmasarik** [comment]
Hey @gkowalski-google, thanks a lot for super quick ack!

All right then, I'll copy-paste it here. :-)

I'm currently trying to find out how to write a policy to check if the given account contains only specified roles. Neither blacklist nor whitelist seems to be working for this use case, as the whitelist is essentially useless here, and in case of the blacklist, I would have to enumerate literally every role except the allowed ones.

I would appreciate any hint or confirmation that the blacklist approach is the only possible one. Attaching the snippet below.

```
- name: Forbid permissive roles on default service accounts
  mode: whitelist  # but in a meaning "allow only specified roles for SA" 
  resource:
    - type: organization
      applies_to: self_and_children
      resource_ids:
        - '*'
  inherit_from_parents: true
  bindings:
    - role: roles/monitoring.viewer
      members:
        - serviceAccount:*-compute@developer.gserviceaccount.com
        - serviceAccount:*@appspot.gserviceaccount.com
    - role: roles/monitoring.metricWriter
      members:
        - serviceAccount:*-compute@developer.gserviceaccount.com
        - serviceAccount:*@appspot.gserviceaccount.com
    - role: roles/logging.logWriter
      members:
        - serviceAccount:*-compute@developer.gserviceaccount.com
        - serviceAccount:*@appspot.gserviceaccount.com
    - role: roles/cloudtrace.agent
      members:
        - serviceAccount:*-compute@developer.gserviceaccount.com
        - serviceAccount:*@appspot.gserviceaccount.com
```

**Comment by gkowalski-google** [comment]
@janmasarik The Forseti IAM scanner actually has a `required` mode which will do what you want: https://forsetisecurity.org/docs/latest/configure/scanner/rules.html#cloud-iam-policy-rules.

FYI this functionality is also available in Config Validator. [Here is a sample policy](https://github.com/forseti-security/policy-library/blob/master/samples/iam_required_roles.yaml) that achieves the same thing. [Forseti docs](https://forsetisecurity.org/docs/latest/configure/migrating-to-rego/index.html#iam-policy) for how to migrate IAM policy to Config Validator.

Let me know if you need anything else.

**Comment by gkowalski-google** [comment]
@janmasarik Any luck? Let me know if you still need help. FYI the Slack link has been fixed on the website.

**Comment by janmasarik** [comment]
Hey @gkowalski-google,

Pardon my ignorance, but based on what I understood, the `required` mode would not check for _additional_ roles that would be granted to default service accounts, which is exactly what we want to check. 

I think `matches` from firewall rules would exactly fit our use-case here as we want to allow **only** specified roles **for a given member** (default service account(s)).

With that said, thanks for recommending Config Validator, and thanks again for your response! It's awesome to see such response time on a big project like this!:)

**Comment by janmasarik** [comment]
Hey @gkowalski-google 👋 ,

I was wondering if my assumptions are correct or not. 😅 

As far as I understand, this would require ~560 _files_[1] with Config Validator as you cannot specify multiple parameters in a single rule. This might be fairly _inconvenient_ + should be updated when you add new roles:

```yaml
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAllowedBindingsConstraintV3
metadata:
  name: restrict_editor_on_default_sa
  annotations:
    description: Default service accounts should not have editor privileges
spec:
  severity: high
  match:
    target:
    - "organizations/**"
  parameters:
    mode: denylist
    role: roles/editor
    members:
      - serviceAccount:*-compute@developer.gserviceaccount.com
      - serviceAccount:*@appspot.gserviceaccount.com
```

[1] current number of roles after listing `gcloud iam roles list | grep roles/ | wc -l`
