### ISSUE TITLE
IAM rule to find a violation in projects under specific folder hierarchy 

### ISSUE THREAD

**Issue by sparthe123** [forseti-security/forseti-security#3826]
Forseti Version: 2.25.2

I'm currently trying to blacklist set of custom IAM roles attached to projects under specific folder hierarchy. I tried the below role which is not finding any violation when I define resource_id to that specific folder path. 
but when I change resource_ids value to * , it is working but it scans the projects in other folders. 
Please check and help me to fix this. 

 ``` 
  - name: Staging Roles Added to Production Project
    mode: blacklist
    resource:
      - type: folder
        applies_to: self_and_children
        resource_ids:
          - 'organizations/xxxxxx/folder/xxxxx'
    inherit_from_parents: true
    bindings:
      - role: 'organizations/xxxxxx/roles/CustomRole32'
        members:
          - user:*
```

**Comment by gkowalski-google** [comment]
Have you tried setting resource_ids to just contain the folder id itself? For example `folder/xxxxx`

**Comment by sparthe123** [comment]
Hi, 

Yes I tried that (as below) , it didn't work either. 

``` 
- name: Staging Roles Added to Production Project
   mode: blacklist
   resource:
     - type: folder
       applies_to: self_and_children
       resource_ids:
         - 'folder/xxxxx'
   inherit_from_parents: true
   bindings:
     - role: 'organizations/xxxxxx/roles/CustomRole32'
       members:
         - user:*
```
