### ISSUE TITLE
Issue with Location Scanner

### ISSUE THREAD

**Issue by soumyadipDe** [forseti-security/forseti-security#3862]
First, help us help you by providing the following information when opening an issue.

 - Foresti Version 2.25.2
 - Issue with Scanner
 - Deployed using Terraform
 - Currently facing following error while scanning for location_rules,
 `"serverMessage": "Error running scanner: LocationScanner: 'Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.2-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n    scanner.run()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.2-py3.6.egg/google/cloud/forseti/scanner/scanners/location_scanner.py\", line 58, in run\n    all_violations = self._find_violations(resources)\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.2-py3.6.egg/google/cloud/forseti/scanner/scanners/location_scanner.py\", line 108, in _find_violations\n    all_violations.extend(violations)\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.2-py3.6.egg/google/cloud/forseti/scanner/audit/location_rules_engine.py\", line 244, in find_violations\n    for violation in rule.find_violations(res):\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.2-py3.6.egg/google/cloud/forseti/scanner/audit/location_rules_engine.py\", line 285, in find_violations\n    applicable_resources.extend(self.applies_to.get('*', []))\nAttributeError: 'str' object has no attribute 'extend'\n'"`

the Location rule file is as below,

```
rules:
  - name: All buckets in organization must be in the EU.
    mode: whitelist
    resource:
      - type: organization
        resource_ids:
          - <org-id>
    applies_to:
      - type: 'bucket'
        resource_ids: '*'
    locations:
      - 'eu*'
  - name: All buckets in organization must not be in US.
    mode: blacklist
    resource:
      - type: organization
        resource_ids:
          - <org-id>
    applies_to:
      - type: 'bucket'
        resource_ids: '*'
    locations:
      - 'us*' 
```

Thanks!
