### ISSUE TITLE
Bucket Rules Need Resource Type

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#752]
The bucket rules should have ```type``` in the resource section to be consistent with the other rules.

```
    resource:
      - type: organization
        resource_ids:
          - <ORG ID>
```
![image](https://user-images.githubusercontent.com/6977544/32181441-991eece0-bd51-11e7-92aa-9095f13eb33c.png)
