### ISSUE TITLE
IAM rules scanner bug: requiring projects to have specific owners

### ISSUE THREAD

**Issue by carise** [forseti-security/forseti-security#799]
Context: https://groups.google.com/a/forsetisecurity.org/forum/#!topic/discuss/0bgBPJPUogw

This rule doesn't work:

```
- name: ... 
   mode: required
   resource:
     - type: project
        applies_to: self
        resource_ids:
          - '*'
   inherit_from_parents: true
   bindings:
     - role: roles/owner
        members:
          - domain:stanford.edu
```
